import 'package:freezed_annotation/freezed_annotation.dart';
import 'package:flutter/foundation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'app_model.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'app_model.g.dart';

@freezed
class AppModel with _$AppModel {
  const factory AppModel({
    required String id,
    required String appName,
    required String appColor,
    required double exchangeRate,
    required String image,
    required int realestateExpirationDays,
    required int homePageAdTake,
    required String appVersion,
     String? androidLink,
     String? iosLink,
     String? huaweiLink,
     required int count,
  }) = _AppModel;

  factory AppModel.fromJson(Map<String, Object?> json)
      => _$AppModelFromJson(json);
}